# This is a basic workflow to help you get started with Actions

name: Markdown Lint
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint-changelog:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Lint changelog file
      uses: avto-dev/markdown-lint@v1
      with:
        config: '.markdownlint.json'
        args: './docs/'